export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const ANIME_ROUTE = "/"
export const ANIME_SEARCH_ROUTE = "/anime"
export const ANIME_PAGE_ROUTE = "/anime/page"
export const USER_ROUTE = "/user"
export const USER_LIST_ROUTE = "/user/list"